trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  dotnetSdkVersion: '6.x'

  
stages:

- stage: 'Test'
  displayName: 'Deploy to the test environment'
  jobs:
  - job: RunUITests
    displayName: 'Run UI tests'
    pool:
      vmImage: 'windows-2019'
    variables:
    - group: 'Release'
    steps: 
#    - task: UseDotNet@2
#      displayName: 'Use .NET SDK $(dotnetSdkVersion)'
#      inputs:
#        version: '$(dotnetSdkVersion)'
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false
    - script: 
        python -m pip install robotframework robotframework-browser
      displayName: 'pip robotframework installs'
    - script: |
        rfbrowser init
      displayName: 'rfbrowser init'
    - script: |
        robot ./Tests.robot
      displayName: 'Run RF Test'
    - script: |
      displayName: 'Transform JMeter output to JUnit'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: output.xml

